# Generated by Django 5.0 on 2024-01-05 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukupna_cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grad', models.CharField(max_length=30)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
