# Generated by Django 5.0 on 2024-01-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0002_narudzba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='date_of_birth',
            new_name='date_of_registration',
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('A', 'Aktivan'), ('N', 'Neaktivan'), ('B', 'Blokiran')], default='A', max_length=1),
        ),
    ]
