# Generated by Django 5.0 on 2024-01-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0003_rename_date_of_birth_myuser_date_of_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='narudzba',
            name='detaljiOIsporuci',
            field=models.CharField(default='r', max_length=255),
        ),
        migrations.AddField(
            model_name='narudzba',
            name='nacinPlacanja',
            field=models.CharField(default='kartica', max_length=30),
        ),
        migrations.AddField(
            model_name='narudzba',
            name='role',
            field=models.CharField(choices=[('U', 'U'), ('P', 'P'), ('I', 'I'), ('O', 'O')], default='P', max_length=1),
        ),
    ]
