# Generated by Django 5.0 on 2024-01-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0006_rename_detaljioisporuci_narudzba_detalji_o_isporuci_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narudzba',
            old_name='nacin_placanja',
            new_name='nacin_plaćanja',
        ),
        migrations.RenameField(
            model_name='narudzba',
            old_name='role',
            new_name='status',
        ),
    ]
