# Generated by Django 5.0 on 2024-01-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0007_rename_nacin_placanja_narudzba_nacin_plaćanja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_proizvoda', models.CharField(max_length=30)),
                ('opis', models.CharField(max_length=30)),
                ('količina', models.IntegerField(max_length=10)),
            ],
        ),
    ]
