# Generated by Django 5.0 on 2024-01-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0008_proizvod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvod',
            name='količina',
            field=models.IntegerField(default=10),
        ),
    ]
