# Generated by Django 5.0 on 2024-01-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0009_alter_proizvod_količina'),
    ]

    operations = [
        migrations.AddField(
            model_name='proizvod',
            name='cijena',
            field=models.DecimalField(decimal_places=2, default=2.55, max_digits=10),
        ),
    ]
