# Generated by Django 5.0 on 2024-01-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0010_proizvod_cijena'),
    ]

    operations = [
        migrations.AddField(
            model_name='proizvod',
            name='boja',
            field=models.CharField(default='plava', max_length=10),
        ),
        migrations.AddField(
            model_name='proizvod',
            name='brend',
            field=models.CharField(default='Vispak', max_length=30),
        ),
        migrations.AddField(
            model_name='proizvod',
            name='datum_dodavanja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proizvod',
            name='grad',
            field=models.CharField(default='Zenica', max_length=30),
        ),
        migrations.AddField(
            model_name='proizvod',
            name='veličina',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='proizvod',
            name='opis',
            field=models.CharField(max_length=255),
        ),
    ]
