# Generated by Django 5.0 on 2024-01-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0012_alter_narudzba_detalji_o_isporuci_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='role',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='narudzba',
            old_name='nacin_plaćanja',
            new_name='način_plaćanja',
        ),
        migrations.AddField(
            model_name='myuser',
            name='grad',
            field=models.CharField(default='Zenica', max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='ime',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='prezime',
            field=models.CharField(max_length=30),
        ),
    ]
