# Generated by Django 5.0 on 2024-01-06 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0014_alter_myuser_grad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukupna_cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proizvodi', models.ManyToManyField(to='TrgovinaApp.proizvod')),
            ],
        ),
    ]
