# Generated by Django 5.0 on 2024-01-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0015_korpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narudzba',
            old_name='način_plaćanja',
            new_name='nacin_placanja',
        ),
    ]
