# Generated by Django 5.0 on 2024-01-14 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0016_rename_način_plaćanja_narudzba_nacin_placanja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_placanja', models.CharField(max_length=10)),
                ('broj_kartice', models.CharField(max_length=30)),
                ('ime_nosioca_kartice', models.CharField(max_length=30)),
                ('datum_isteka', models.DateField(blank=True, null=True)),
                ('ukupan_iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('narudzba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrgovinaApp.narudzba')),
            ],
        ),
    ]
