# Generated by Django 5.0 on 2024-01-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0017_placanje'),
    ]

    operations = [
        migrations.AddField(
            model_name='narudzba',
            name='placeno',
            field=models.BooleanField(default=False),
        ),
    ]
