# Generated by Django 5.0 on 2024-01-15 22:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0018_narudzba_placeno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst_recenzije', models.CharField(max_length=255)),
                ('ocjena', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('datum_postavke', models.DateField(blank=True, null=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrgovinaApp.proizvod')),
            ],
        ),
    ]
