# Generated by Django 5.0 on 2024-01-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrgovinaApp', '0019_recenzija'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_kategorije', models.CharField(max_length=30)),
                ('opis_kategorije', models.CharField(max_length=255)),
            ],
        ),
    ]
